[2025-04-17T21:32:02.301+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-17T21:32:02.337+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_demo.download_data manual__2025-04-17T21:32:00.699900+00:00 [queued]>
[2025-04-17T21:32:02.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_demo.download_data manual__2025-04-17T21:32:00.699900+00:00 [queued]>
[2025-04-17T21:32:02.351+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-04-17T21:32:02.379+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_data> on 2025-04-17 21:32:00.699900+00:00
[2025-04-17T21:32:02.384+0000] {standard_task_runner.py:63} INFO - Started process 933 to run task
[2025-04-17T21:32:02.388+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_demo', 'download_data', 'manual__2025-04-17T21:32:00.699900+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp7btecou_']
[2025-04-17T21:32:02.392+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask download_data
[2025-04-17T21:32:02.422+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-17T21:32:02.464+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_demo.download_data manual__2025-04-17T21:32:00.699900+00:00 [running]> on host b3f0d5cbc6df
[2025-04-17T21:32:02.578+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_demo' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-17T21:32:00.699900+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-17T21:32:00.699900+00:00'
[2025-04-17T21:32:02.580+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-17T21:32:03.216+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-17T21:32:03.217+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-17T21:32:03.228+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline_demo, task_id=download_data, run_id=manual__2025-04-17T21:32:00.699900+00:00, execution_date=20250417T213200, start_date=20250417T213202, end_date=20250417T213203
[2025-04-17T21:32:03.259+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-17T21:32:03.286+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-17T21:32:03.296+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
