[2025-05-02T02:22:34.293+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-02T02:22:34.349+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_pipeline_demo.transform_data_1 manual__2025-05-02T02:22:25.123693+00:00 [queued]>
[2025-05-02T02:22:34.364+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_pipeline_demo.transform_data_1 manual__2025-05-02T02:22:25.123693+00:00 [queued]>
[2025-05-02T02:22:34.367+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-05-02T02:22:34.412+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_data_1> on 2025-05-02 02:22:25.123693+00:00
[2025-05-02T02:22:34.429+0000] {standard_task_runner.py:63} INFO - Started process 2599 to run task
[2025-05-02T02:22:34.445+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_pipeline_demo', 'transform_data_1', 'manual__2025-05-02T02:22:25.123693+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpc7adm82x']
[2025-05-02T02:22:34.451+0000] {standard_task_runner.py:91} INFO - Job 27: Subtask transform_data_1
[2025-05-02T02:22:34.528+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.10/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-02T02:22:34.605+0000] {task_command.py:426} INFO - Running <TaskInstance: data_pipeline_demo.transform_data_1 manual__2025-05-02T02:22:25.123693+00:00 [running]> on host b3f0d5cbc6df
[2025-05-02T02:22:34.791+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='data_pipeline_demo' AIRFLOW_CTX_TASK_ID='transform_data_1' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T02:22:25.123693+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T02:22:25.123693+00:00'
[2025-05-02T02:22:34.793+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-02T02:22:34.863+0000] {logging_mixin.py:188} INFO - Tache transform_data bien executee
[2025-05-02T02:22:34.863+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-05-02T02:22:34.865+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-02T02:22:34.883+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_pipeline_demo, task_id=transform_data_1, run_id=manual__2025-05-02T02:22:25.123693+00:00, execution_date=20250502T022225, start_date=20250502T022234, end_date=20250502T022234
[2025-05-02T02:22:34.939+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-05-02T02:22:34.982+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-02T02:22:35.000+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
